# Generated by Django 3.2.5 on 2021-09-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
