# Generated by Django 4.2.3 on 2023-07-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsearch', '0003_alter_apartment_currency_alter_apartment_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Если парсер получил 404 ошибку, то мы помечаем объявление как удаленное.', null=True, verbose_name='Дата удаления на сайте.'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='viewed_at',
            field=models.DateTimeField(blank=True, help_text='Дата, когда парсер в последний раз видел это объявление на сайте.', null=True, verbose_name='Дата последнего просмотра.'),
        ),
    ]
