version: '3.3'

services:
  postgres:
    image: postgres:13-alpine
    container_name: hsearch_db
    restart: always
    environment:
      POSTGRES_PASSWORD: hsearch
      POSTGRES_DB: hsearch
      POSTGRES_USER: hsearch
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 65432:5432

  api:
    build:
      context: api/
    image: "registry.gitlab.com/my_house/my_house_api:latest"
    container_name: myhouse_api
    environment:
      DJANGO_DEBUG: 'true'
      DJANGO_DB_HOST: hsearch_db
      DJANGO_DB_PORT: 65432
    ports:
      - 8080:8080

volumes:
  pgdata:
