version: '3.3'

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: hsearch_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: hsearch
      POSTGRES_USER: hsearch_srv
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "25432:5432"

  redis:
    image: redis:7.0-alpine
    restart: always
    container_name: hsearch_redis
    ports:
      - "26379:6379"

volumes:
  pgdata:
