version: '3.3'

services:
  postgres:
    image: postgres:13-alpine
    container_name: hsearch_db
    restart: always
    environment:
      POSTGRES_PASSWORD: hsearch
      POSTGRES_DB: hsearch
      POSTGRES_USER: hsearch
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 65432:5432

  admin:
    build:
      dockerfile: Dockerfile.admin
      context: .
    container_name: hsearch_admin
    environment:
      DJANGO_DEBUG: true
      DJANGO_DB_HOST: hsearch_db
      DJANGO_DB_PORT: 65432
    ports:
      - 8080:8080

volumes:
  pgdata:
