version: '3.3'

services:
  app:
    image: ghcr.io/aastashov/easyhome:dev
    container_name: easyhome
    command: /src/bin/gunicorn.sh
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      .env
    ports:
      - "127.0.0.1:8000:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1-alpine
    container_name: easyhome_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: easyhome
      POSTGRES_USER: easyhome_srv
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "25432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    container_name: easyhome_redis
    ports:
      - "26379:6379"

volumes:
  pgdata:
