version: '3.3'

services:
  app:
    image: comov/hsearch:latest
    container_name: hsearch
    command: hsearch withmigrate -dir=/srv/migrations
    restart: always
    env_file:
      - .env
    volumes:
      - /srv/hsearch/news.json:/news.json
    networks:
      - my_house
    logging:
      driver: syslog
      options:
        tag: docker/hsearch

  api:
    image: ghcr.io/comov/hsearch:6
    container_name: hsearch_api
    restart: always
    command: /src/bin/gunicorn.sh
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: hsearch.ik.kg
      LETSENCRYPT_HOST: hsearch.ik.kg
      LETSENCRYPT_EMAIL: alexander.astashov.vl@gmail.com
    networks:
      - hsearch
    volumes:
      - ./static:/src/static
    expose:
      - "8080"
    logging:
      driver: syslog
      options:
        tag: docker/hsearch_api

  postgres:
    image: postgres:13-alpine
    container_name: hsearch_db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_house
      - hsearch
    ports:
      - "45432:5432"
    logging:
      driver: syslog
      options:
        tag: docker/hsearch_db

volumes:
  pgdata:

networks:
  my_house:
    external: true
  hsearch:
    external: true
