version: '3.3'

services:
  app:
    image: ghcr.io/aastashov/easyhome:latest
    container_name: easyhome
    restart: always
    command: /src/bin/gunicorn.sh
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: easyhome.ik.kg
      LETSENCRYPT_HOST: easyhome.ik.kg
      LETSENCRYPT_EMAIL: alexander.astashov.vl@gmail.com
    networks:
      - easyhome
    volumes:
      - ./static:/src/static
    expose:
      - "8080"
    logging:
      driver: syslog
      options:
        tag: docker/easyhome_api

  postgres:
    image: postgres:13-alpine
    container_name: easyhome_db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_house
      - easyhome
    ports:
      - "45432:5432"
    logging:
      driver: syslog
      options:
        tag: docker/easyhome_db

volumes:
  pgdata:

networks:
  my_house:
    external: true
  easyhome:
    external: true
