version: '2'

networks:
  easyhome:
    external: true

services:
  nginx:
    container_name: nginx
    image: nginx:1.25-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/docker/nginx/config/conf.d:/etc/nginx/conf.d
      - /opt/docker/nginx/config/vhost.d:/etc/nginx/vhost.d
      - /opt/docker/nginx/config/html:/usr/share/nginx/html
      - /opt/docker/nginx/config/certs:/etc/nginx/certs:ro
      - /opt/docker/easyhome/static/:/app/ik.kg/static/
    logging:
      driver: syslog
      options:
        tag: "docker/nginx"
    networks:
      - easyhome

  nginx-gen:
    container_name: nginx-gen
    image: jwilder/docker-gen
    restart: always
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /opt/docker/nginx/config/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging:
      driver: syslog
      options:
        tag: "docker/gen"
    networks:
      - easyhome
    depends_on:
      - nginx

  nginx-letsencrypt:
    container_name: nginx-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - NGINX_PROXY_CONTAINER=nginx
    volumes_from:
      - nginx
    volumes:
      - /opt/docker/nginx/config/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: syslog
      options:
        tag: "docker/nginx-letsencrypt"
    networks:
      - easyhome
    depends_on:
      - nginx-gen
