name: Run Tests and Linters

on:
  push:
    branches-ignore:
      - "main"
  workflow_call:

env:
  DJANGO_SECRET_KEY: "secret key"
  DJANGO_ALLOWED_HOSTS: "*"

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.3.2"

      - name: Install dependencies
        run: make install-ci

      - name: Run lint
        run: make lint

      - name: Test with pytest
        run: make test-ci
